### ISSUE TITLE
Demo page is mining ethereum?

### ISSUE THREAD

**Issue by william-bratches** [pbojinov/react-iframe-comm#10]
There's been a lot of concern over NPM security lately, and wanted to ensure that this was isolated to the demo page and not the package itself.

```
var web3 = new Web3(inpageProvider);
web3.setProvider = function () {
  log.debug('MetaMask - overrode web3.setProvider');
};
log.debug('MetaMask - injected web3');
// export global web3, with usage-detection
setupDappAutoReload(web3, inpageProvider.publicConfigStore);

// set web3 defaultAccount

inpageProvider.publicConfigStore.subscribe(function (state) {
  web3.eth.defaultAccount = state.selectedAddress;
});
```

**Comment by pbojinov** [comment]
There should not be any mining going on. Are you running the MetaMask extension on your browser? Where do you see that particular snippet of code that you pasted?

I don't see any reference to web3 or MetaMask on [react storybook demo page](https://pbojinov.github.io/react-iframe-comm/) or in the source of the storyboard code.
