### ISSUE TITLE
Impossible to install this package 

### ISSUE THREAD

**Issue by LenaNesg** [pbojinov/react-iframe-comm#8]
npm install react-iframe-comm --save
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-iframe-comm" "--save"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 no such package available : @kadira/storybook-deployer
npm ERR! 404npm ERR! 404  '@kadira/storybook-deployer' is not in the npm registry.npm ERR! 404 You should bug the author to publish it (or use the nameyourself!)
npm ERR! 404 It was specified as a dependency of 'react-iframe-comm'npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp\npm-debug.log

This is my log :
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '--save',
1 verbose cli   '@kadira/storybook-deployer' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData @kadira/storybook-deployer
8 silly fetchNamedPackageData @kadira/storybook-deployer
9 silly mapToRegistry name @kadira/storybook-deployer
10 silly mapToRegistry scope (from package name) @kadira
11 verbose mapToRegistry no registry URL found in name for scope @kadira
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry http://localhost:4873/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@kadira/storybook-deployer',
14 silly mapToRegistry   scope: '@kadira',
14 silly mapToRegistry   escapedName: '@kadira%2fstorybook-deployer',
14 silly mapToRegistry   name: '@kadira/storybook-deployer',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri http://localhost:4873/@kadira%2fstorybook-deployer
16 verbose request uri http://localhost:4873/@kadira%2fstorybook-deployer
17 verbose request no auth needed
18 info attempt registry request try #1 at 09:15:31
19 verbose request using bearer token for auth
20 verbose request id 9f1fa704057cf93f
21 http request GET http://localhost:4873/@kadira%2fstorybook-deployer
22 http 404 http://localhost:4873/@kadira%2fstorybook-deployer
23 verbose headers { 'x-powered-by': 'Sinopia/1.4.0',
23 verbose headers   'content-type': 'application/json; charset=utf-8',
23 verbose headers   'content-length': '43',
23 verbose headers   etag: 'W/"2b-d418f262"',
23 verbose headers   vary: 'Accept-Encoding',
23 verbose headers   'x-status-cat': 'http://flic.kr/p/aV6juR',
23 verbose headers   date: 'Mon, 20 Nov 2017 07:15:31 GMT',
23 verbose headers   connection: 'keep-alive' }
24 silly get cb [ 404,
24 silly get   { 'x-powered-by': 'Sinopia/1.4.0',
24 silly get     'content-type': 'application/json; charset=utf-8',
24 silly get     'content-length': '43',
24 silly get     etag: 'W/"2b-d418f262"',
24 silly get     vary: 'Accept-Encoding',
24 silly get     'x-status-cat': 'http://flic.kr/p/aV6juR',
24 silly get     date: 'Mon, 20 Nov 2017 07:15:31 GMT',
24 silly get     connection: 'keep-alive' } ]
25 silly fetchPackageMetaData Error: no such package available : @kadira/storybook-deployer
25 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
25 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
25 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
25 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
25 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
25 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
25 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
25 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
25 silly fetchPackageMetaData  error for @kadira/storybook-deployer { Error: no such package available : @kadira/storybook-deployer
25 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
25 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
25 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
25 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
25 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
25 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
25 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
25 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
25 silly fetchPackageMetaData   pkgid: '@kadira/storybook-deployer',
25 silly fetchPackageMetaData   statusCode: 404,
25 silly fetchPackageMetaData   code: 'E404' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: no such package available : @kadira/storybook-deployer
30 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
30 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
30 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
30 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
30 verbose stack     at emitTwo (events.js:106:13)
30 verbose stack     at Request.emit (events.js:191:7)
30 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
30 verbose stack     at emitOne (events.js:96:13)
30 verbose stack     at Request.emit (events.js:188:7)
30 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
31 verbose statusCode 404
32 verbose pkgid @kadira/storybook-deployer
33 verbose cwd C:\GIT\SocialACR\SocialACR\Leverate.SocialACR.WebApp
34 error Windows_NT 10.0.15063
35 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "@kadira/storybook-deployer"
36 error node v6.11.1
37 error npm  v3.10.10
38 error code E404
39 error 404 no such package available : @kadira/storybook-deployer
40 error 404
41 error 404 '@kadira/storybook-deployer' is not in the npm registry.
42 error 404 You should bug the author to publish it (or use the name yourself!)
43 error 404 Note that you can also install from a
44 error 404 tarball, folder, http url, or git url.
45 verbose exit [ 1, true ]

**Comment by pbojinov** [comment]
I will try to reproduce. What version of node are you using?

Thank You,
Petar

**Comment by LenaNesg** [comment]
node v6.11.1
npm v3.10.10
Windows_NT 10.0.15063

I solved this problem by coping your controller IframeComm under my project. It works perfect. Thanks :)

**Comment by pbojinov** [comment]
I don't have a windows NT box to test this one but I was able to successfully install it on a Windows machine with node v6 and npm v3. 

Closing for now.
